export const FETCH_TWEETS = 'FETCH_TWEETS';
export const FETCH_TWEETS_PENDING = 'FETCH_TWEETS_PENDING';
export const FETCH_TWEETS_FULLFILLED = 'FETCH_TWEETS_FULLFILLED';
export const FETCH_TWEETS_REJECTED = 'FETCH_TWEETS_REJECTED';
export const UPDATE_TWEET = 'UPDATE_TWEET';

export const FETCH_USERS_FULLFILLED = 'FETCH_USERS_FULLFILLED';

export const FETCH_API = 'FETCH_API';